# Generated by Django 4.0.2 on 2022-03-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_username_suppliers_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='supplies',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Supplies',
        ),
    ]
