# Generated by Django 4.0.2 on 2022-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sales_product_sales_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
