# Generated by Django 4.0.2 on 2022-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='supplies',
            field=models.CharField(max_length=100),
        ),
    ]
