# Generated by Django 4.0.2 on 2022-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_supplies_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='supplied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
