# Generated by Django 4.0.2 on 2022-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_supplies_supplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplies',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='supplies',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
