# Generated by Django 4.0.2 on 2022-03-20 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0008_rename_username_supplies_username_supplies_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='username',
        ),
        migrations.AddField(
            model_name='supplies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
