# Generated by Django 4.0.2 on 2022-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
