# Generated by Django 4.0.2 on 2022-03-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_ordered_from_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ordered_from',
            new_name='ordered_by',
        ),
    ]
